const PDI_KEY="cmivet-avaliacoes-pdi";let data={};const toast=document.querySelector("#toast");
function showToast(m){toast.textContent=m;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2600)}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function badge(s){const l={pending:"Pendente",progress:"Em andamento",completed:"Concluída"};return `<span class="badge">${l[s]||s}</span>`}
function getPdis(){try{return JSON.parse(localStorage.getItem(PDI_KEY))||[]}catch{return[]}}function savePdis(i){localStorage.setItem(PDI_KEY,JSON.stringify(i))}
function renderMetrics(){const e=data.experience||[],p=data.performance||[],d=getPdis();document.querySelector("#metricExperience").textContent=e.length;document.querySelector("#metricPerformance").textContent=p.length;document.querySelector("#metricPdi").textContent=d.filter(i=>i.status!=="completed").length;document.querySelector("#metricCompleted").textContent=[...e,...p].filter(i=>i.status==="completed").length}
function renderStatus(){const all=[...(data.experience||[]),...(data.performance||[])],c={Pendentes:all.filter(i=>i.status==="pending").length,"Em andamento":all.filter(i=>i.status==="progress").length,Concluídas:all.filter(i=>i.status==="completed").length},max=Math.max(...Object.values(c),1);document.querySelector("#statusChart").innerHTML=Object.entries(c).map(([l,n])=>`<div class="bar-row"><div class="bar-label">${l}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.round(n/max*100)}%"></div></div><div class="bar-value">${n}</div></div>`).join("")}
function renderPending(){const l=[...(data.experience||[]),...(data.performance||[])].filter(i=>i.status!=="completed").slice(0,6);document.querySelector("#pendingList").innerHTML=l.length?l.map(i=>`<article class="list-item"><h4>${esc(i.employee)}</h4><p>${esc(i.type||i.cycle)} • ${esc(i.department)}</p><div class="list-meta">${badge(i.status)}<span class="badge">${esc(i.dueDate||i.stage)}</span></div></article>`).join(""):`<div class="empty">Nenhuma pendência.</div>`}
function renderExperience(f="all"){let l=data.experience||[];if(f!=="all")l=l.filter(i=>i.period===f);document.querySelector("#experienceGrid").innerHTML=l.map(i=>`<article class="record-card"><h4>${esc(i.employee)}</h4><p>${esc(i.role)} • ${esc(i.department)}</p><div class="list-meta"><span class="badge">${i.period} dias</span>${badge(i.status)}</div><div class="record-footer"><span>${esc(i.dueDate)}</span><span>${esc(i.manager)}</span></div></article>`).join("")}
function renderPerformance(){document.querySelector("#performanceGrid").innerHTML=(data.performance||[]).map(i=>`<article class="record-card"><h4>${esc(i.employee)}</h4><p>${esc(i.cycle)} • ${esc(i.department)}</p><div class="list-meta">${badge(i.status)}<span class="badge">${esc(i.stage)}</span></div><div class="record-footer"><span>${esc(i.manager)}</span><span>${esc(i.score||"-")}</span></div></article>`).join("")}
function renderClimate(){const c=data.climate||{};document.querySelector("#climateParticipation").textContent=`${c.participation||0}%`;document.querySelector("#climateBar").style.width=`${c.participation||0}%`;document.querySelector("#climateText").textContent=`${c.responses||0} respostas de ${c.totalEmployees||0} colaboradores.`;document.querySelector("#climateScore").textContent=String(c.score||0).replace(".",",");document.querySelector("#departmentChart").innerHTML=(c.departments||[]).map(i=>`<div class="bar-row"><div class="bar-label">${esc(i.name)}</div><div class="bar-track"><div class="bar-fill" style="width:${i.participation}%"></div></div><div class="bar-value">${i.participation}%</div></div>`).join("")}
function renderPdis(){const l=getPdis();document.querySelector("#pdiList").innerHTML=l.length?l.map((i,x)=>`<article class="list-item"><h4>${esc(i.employee)}</h4><p>${esc(i.goal)}</p><div class="list-meta"><span class="badge">${esc(i.owner)}</span><span class="badge">${esc(i.deadline)}</span><button class="btn ghost" data-done="${x}">${i.status==="completed"?"Concluído":"Concluir"}</button></div></article>`).join(""):`<div class="empty">Nenhum PDI registrado.</div>`;document.querySelectorAll("[data-done]").forEach(b=>b.addEventListener("click",()=>{const a=getPdis();a[+b.dataset.done].status="completed";savePdis(a);renderPdis();renderMetrics();showToast("PDI concluído.")}))}
function renderManagers(){document.querySelector("#managerGrid").innerHTML=(data.managers||[]).map(i=>`<article class="manager-card"><h4>${esc(i.name)}</h4><p>${esc(i.department)}</p><ul><li>${i.teamSize} colaboradores</li><li>${i.pending} avaliações pendentes</li><li>${i.feedbacks} feedbacks pendentes</li></ul></article>`).join("")}
function renderAll(){renderMetrics();renderStatus();renderPending();renderExperience();renderPerformance();renderClimate();renderPdis();renderManagers()}
document.querySelector("#filter45").onclick=()=>renderExperience("45");document.querySelector("#filter90").onclick=()=>renderExperience("90");document.querySelector("#filterAll").onclick=()=>renderExperience("all");
document.querySelector("#pdiForm").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),a=getPdis();a.push({employee:f.get("employee").trim(),goal:f.get("goal").trim(),action:f.get("action").trim(),owner:f.get("owner").trim(),deadline:f.get("deadline"),status:"pending"});savePdis(a);e.currentTarget.reset();renderPdis();renderMetrics();showToast("PDI salvo com sucesso.")});
function openView(v){document.querySelectorAll(".page-section").forEach(s=>s.classList.toggle("active",s.id===v));document.querySelectorAll(".menu-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));const t={dashboard:"Dashboard de Avaliações",experiencia:"Avaliação de Experiência",desempenho:"Avaliação de Desempenho",clima:"Pesquisa de Clima",pdi:"Plano de Desenvolvimento Individual",gestor:"Painel do Gestor"};document.querySelector("#pageTitle").textContent=t[v]||"Avaliações";document.querySelector("#sidebar").classList.remove("open")}
document.querySelectorAll(".menu-item").forEach(b=>b.onclick=()=>openView(b.dataset.view));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>openView(b.dataset.go));document.querySelector("#mobileMenu").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");
fetch(`avaliacoes.json?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{data=j;renderAll()}).catch(()=>showToast("Não foi possível carregar os dados."));
